project:
  type: website
  output-dir: docs # Standard for GitHub Pages hosting

website:
  title: "Yu (Tina) Chen"
  search: false
  description: "Developmental Psychologist"
  navbar:
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd
    right: []

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
