---
title: "Publications"
---

## Selected Peer-Reviewed Articles

- Canfield, C. F., Finegood, E., Chen, Y., Lalwani, P., Sadler, R. C., O’Connell, L. B., Gutierrez, J., Milton, A., Loney, K., & Mendelsohn, A. L. (2026). Neighborhood disorder and infant screen time: Buffering effects of the PlayReadVIP parent–child program. *Child Development*. [View Article](https://doi.org/10.1093/chidev/aacag109)

- Chen, Y., Canfield, C. F., Roby, E., Weisleder, A., Farinelli, M., Cates, C. B., & Mendelsohn, A. (2026). Parenting intervention in pediatric primary care promotes child mental health: Evidence from a randomized controlled trial of PlayReadVIP. *The Journal of Pediatrics*. [View Article](https://doi.org/10.1016/j.jpeds.2026.115038)

- Chen, Y., Miller, E. B., Kuttamperoor, J., Guevara, V., Walther, D., Tyrrell, H., Yin, S. H., Huang, K., & Canfield, C. F. (2026). Integrating evidence-based early relational health programs into pediatric primary care: A mixed methods study. *Academic Pediatrics*. [View Article](doi.org/10.1016/j.acap.2026.103262)

- Chen, Y., Canfield, C. F., Finegood, E. D., Gutierrez, J., Milton, A., Loney, K., O'Connell, L. K., & Mendelsohn, A. L. (2026). Family engagement in an early childhood preventive parenting program: Innovative methods for examining sociodemographic, psychosocial, and contextual predictors. *Prevention Science*. [View Article](doi.org/10.1007/s11121-025-01873-0)

- Chen, Y., Canfield, C. F., Finegood, E. D., Gutierrez, J., Williams, S., O'Connell, L. K., & Mendelsohn, A. L. (2025). Family stress model and parenting in infancy: Social support and parenting self-efficacy as resilience factors. *Journal of Family Psychology*. [View Article](doi.org/10.1037/fam0001341)

- Chen, Y., Cabrera, N. J., Sudduth, C. A., & Reich, S. (2024). Contributions of mothers’ and fathers’ shared book reading with infants at 9 months to language skills at 18 months in ethnically and socioeconomically diverse families. *Infant and Child Development*. [View Article](doi.org/10.1002/icd.2516)

- Chen, Y., Cabrera, N. J., & Reich, S. (2023). Mother-child and father-child “serve and return” interactions at 9 months: Associations with children's language skills at 18 and 24 months. *Infant Behavior and Development*. [View Article](doi.org/10.1016/j.infbeh.2023.101894)

- Silver, A. M., Chen, Y., Smith, D. K., Tamis-LeMonda, C. S., Cabrera, N. J., & Libertus, M. E. (2023). Mothers’ and fathers’ engagement in math activities with their toddler sons and daughters: The moderating role of parental math beliefs. *Frontiers in Psychology*. [View Article](doi.org/10.3389/fpsyg.2023.1124056)

## Selected Articles for a Broader Audience

- Chen, Y. (2024). Parent-child interactions support early language development in diverse families. *International Congress of Infant Studies: The Baby Blog*. [View Article](https://infantstudies.org/parent-child-interactions-support-early-language-development-in-diverse-families/)

- Cabrera, N. J., Chen, Y., Alonso, A., West, J., & Fagan, J. (2021). Latino parents report positive co-parenting and parent-child interactions that vary by gender and nativity. *National Research Center on Hispanic Children & Families*. [View Article](https://www.hispanicresearchcenter.org/research-resources/Latino-Parents-Report-Positive-Co-parenting-and-Parent-Child-Interactions-that-Vary-by-Gender-and-Nativity/)
